### ISSUE TITLE
table/figure/reference citations not imported

### ISSUE THREAD

**Issue by aliceh75** [pensoft/dev#12]
Hello,

I have imported a document using the API. The submitted XML contained table, figure and reference citations. Those are not present in the imported document.

Here is an example (from the actual XML that was submitted) of a table citation in the introduction field:

``` xml
<introduction>
  <fields>
    <introduction>
      <value><div><p>
        <tbls-citation citation_id="1">Table 1</tbls-citation>
      </p></div></value></introduction>
...
```

The `citation_id` matches the `id` attribute on the corresponding table element:

``` xml
<tables><table id="1"><fields>...
```

Note that I have done more tests, with fields that also included content, and the results are the same. The results are also the same for reference and figure citations. The fact the id used here is '1' does not make a difference - using other larger and random ids (just in case '1' clashes with internal ids somewhere) has the same result.

**Comment by Biserkov** [comment]
Yes, this feature is not yet implemented.

**Comment by petarg** [comment]
Citations are now supported. For more info check http://pwt.pensoft.net/dev/
