### ISSUE TITLE
Introduction section

### ISSUE THREAD

**Issue by rodroug** [pensoft/dev#13]
Hello,
After writing up contents within the 'Introduction' section (advanced editing mode) and saving changes, the entire section is absent from the manuscript preview. 
This isn't a consistent glitch though as the section was present when opening the preview previously, but now it's gone again...
Thanks and congrats for the great tools!
Rodolphe

**Comment by petarg** [comment]
Hi, we have reproduced the problem and are working on fixing it :)
Petar

**Comment by petarg** [comment]
Should be fixed now,
Petar

**Comment by rodroug** [comment]
Thank you Petar!
Yes, problem fixed - all good now.
Best regards
Rodolphe

Le 11/08/2014 10:44, petarg a écrit :

> Should be fixed now,
> Petar
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/pensoft/dev/issues/13#issuecomment-51754832.

## 

_Rodolphe Rougerie, /PhD
/_INRA-URZF Postdoctoral Fellow & iBOL Lepidoptera Campaign Coordinator 

## (link http://www.lepbarcoding.org)

INRA Orléans - Unité de Recherche en Zoologie Forestière

2163 Avenue de la Pomme de Pin

CS 40001 Ardon

45075 Orléans Cedex 2

---

Tel. 33(0)2 38 41 78 00 / Fax.33(0)2 38 41 78 79

Email: rrougeri@gmail.com mailto:rrougeri@gmail.com
Skype contact: rodroug (Orléans, France)
Personal Webpage: click here 
http://rodolphe.rougerie.pagesperso-orange.fr/

ResearchGate Webpage: click here 
https://www.researchgate.net/profile/Rodolphe_Rougerie/
