### ISSUE TITLE
Required field inconsistencies

### ISSUE THREAD

**Issue by aliceh75** [pensoft/dev#4]
I notice that the Pensoft Writting Tool has a number of required fields that are not required in the XML schema.

For instance, in the systematics section of a taxonomic paper, "select_type" (extant/fossil) is not required: 

<xsd:element name="select_type" type="fieldtaxon_treatment_status_typesEmpty" minOccurs="0"/>

However the equivalent field is required in the Pensoft Writting Tool. The same problem applies to other fields too.

**Comment by Biserkov** [comment]
Yes, the API schema is intentionally more relaxed than the interface
